/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GenerationEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'layoutStyle' : IDL.Text,
  'timestamp' : IDL.Int,
  'prompt' : IDL.Text,
  'colorScheme' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteGeneration' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getGeneration' : IDL.Func([IDL.Nat], [IDL.Opt(GenerationEntry)], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(GenerationEntry)], ['query']),
  'saveGeneration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GenerationEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'layoutStyle' : IDL.Text,
    'timestamp' : IDL.Int,
    'prompt' : IDL.Text,
    'colorScheme' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteGeneration' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getGeneration' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(GenerationEntry)],
        ['query'],
      ),
    'getHistory' : IDL.Func([], [IDL.Vec(GenerationEntry)], ['query']),
    'saveGeneration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };